### ISSUE TITLE
Single Declarations Question

### ISSUE THREAD

**Issue by frekyll** [mdo/feedback#148]
Howdy @mdo,

I've recently found myself in a pickle on deciding how to write CSS when there are multiple selectors with one declaration. Here's where I'd like your opinion:

Would you write something like this?

```css
.selector,
.another-selector { width: 60px; }
```

Or something like this?

```css
.selector,
.another-selector { 
  width: 60px; 
}
```

I'm trying to figure out which method has better readability. Thanks!
